name: Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Link
        run: |
          yarn link

      - name: (swc + spack) three.js
        run: |
          mkdir -p integration-tests/three.js
          git clone --depth 1 https://github.com/mrdoob/three.js.git integration-tests/three.js

          cd integration-tests/three.js
          npm install @swc/core @swc/cli --save-dev
          npm install
          yarn link @swc/cli

          tee .swcrc <<EOF
          {
            "jsc": {
                "target": "es2019",
                "parser": {
                  "syntax": "ecmascript",
                  "dynamicImport": true
                }
            },
            "module": {
                "type": "commonjs"
            }
          }
          EOF

          echo "Run swc sync"
          yarn swc --sync src -d ./build/
          yarn swc --sync editor -d ./build-editor/

          rm -rf build 

          echo "Run swc async"
          yarn swc src -d ./build/
          yarn swc editor -d ./build-editor/


          tee spack.config.js <<EOF
          module.exports = {
            entry: {
              web: __dirname + "/src/Three.js",
            },
            output: {
              path: __dirname + "/out",
            },
          };
          EOF

          echo "Run spack"
          yarn spack
      - name: (swc + spack) rxjs
        run: |
          mkdir -p integration-tests/rxjs
          git clone --depth 1 https://github.com/ReactiveX/rxjs.git integration-tests/rxjs

          cd integration-tests/rxjs
          npm install @swc/core @swc/cli --save-dev
          npm install
          yarn link @swc/cli

          tee .swcrc <<EOF
          {
            "jsc": {
                "target": "es2019",
                "parser": {
                  "syntax": "typescript",
                  "dynamicImport": true
                }
            },
            "module": {
                "type": "commonjs"
            }
          }
          EOF

          echo "Run swc sync"
          yarn swc --sync src -d ./build/
          yarn swc --sync spec -d ./build-spec/

          rm -rf build 

          echo "Run swc async"
          yarn swc src -d ./build/
          yarn swc spec -d ./build-spec/

          tee spack.config.js <<EOF
          module.exports = {
            entry: {
              web: __dirname + "/src/index.ts",
            },
            output: {
              path: __dirname + "/out",
            },
          };
          EOF

          echo "Run spack"
          yarn spack
